import os from 'node:os';import path from 'node:path';import { mkdtemp,readFile,rm } from 'node:fs/promises';import { commandExists,runProcess } from './process.js';
const escapeApple=(value:string)=>value.replaceAll('\\','\\\\').replaceAll('"','\\"');
export function parseShortcut(value:string){const parts=value.toUpperCase().split('+').map((part)=>part.trim()).filter(Boolean);return{modifiers:parts.slice(0,-1),key:parts.at(-1)??''};}
export class DesktopController{
  async screenshot(){const dir=await mkdtemp(path.join(os.tmpdir(),'nexus-shot-'));const file=path.join(dir,'screen.png');try{if(process.platform==='darwin')await runProcess(['screencapture','-x',file],{timeoutMs:15_000});else if(await commandExists('grim'))await runProcess(['grim',file],{timeoutMs:15_000});else if(await commandExists('gnome-screenshot'))await runProcess(['gnome-screenshot','-f',file],{timeoutMs:15_000});else throw new Error('No screenshot backend found (install grim or gnome-screenshot)');const data=await readFile(file);return{mimeType:'image/png',dataBase64:data.toString('base64')};}finally{await rm(dir,{recursive:true,force:true});}}
  async click(x:number,y:number,button:'left'|'right'='left'){if(process.platform==='darwin'){const type=button==='right'?'right':'left';const script=`import CoreGraphics\nlet p=CGPoint(x:${Math.round(x)},y:${Math.round(y)})\nlet d=CGEvent(mouseEventSource:nil,mouseType:.${type}MouseDown,mouseCursorPosition:p,mouseButton:.${type})!\nlet u=CGEvent(mouseEventSource:nil,mouseType:.${type}MouseUp,mouseCursorPosition:p,mouseButton:.${type})!\nd.post(tap:.cghidEventTap);u.post(tap:.cghidEventTap)`;return runProcess(['swift','-e',script],{timeoutMs:20_000});}if(await commandExists('xdotool'))return runProcess(['xdotool','mousemove',String(Math.round(x)),String(Math.round(y)),'click',button==='right'?'3':'1'],{timeoutMs:10_000});throw new Error('No Linux click backend found (install xdotool; ydotool adapter is a future optional backend)');}
  async type(text:string){if(process.platform==='darwin')return runProcess(['osascript','-e',`tell application "System Events" to keystroke "${escapeApple(text)}"`],{timeoutMs:30_000});if(await commandExists('wtype'))return runProcess(['wtype',text],{timeoutMs:30_000});if(await commandExists('xdotool'))return runProcess(['xdotool','type','--delay','0',text],{timeoutMs:30_000});throw new Error('No Linux typing backend found (install wtype or xdotool)');}
  async key(value:string){const shortcut=parseShortcut(value);if(process.platform==='darwin'){const special:Record<string,number>={ENTER:36,RETURN:36,ESCAPE:53,ESC:53,TAB:48,SPACE:49,DELETE:51,BACKSPACE:51};const mods=shortcut.modifiers.map((m)=>m==='CMD'||m==='COMMAND'?'command down':m==='CTRL'||m==='CONTROL'?'control down':m==='ALT'||m==='OPTION'?'option down':m==='SHIFT'?'shift down':'').filter(Boolean);const using=mods.length?` using {${mods.join(', ')}}`:'';const expr=special[shortcut.key]!==undefined?`key code ${special[shortcut.key]}${using}`:`keystroke "${escapeApple(shortcut.key.toLowerCase())}"${using}`;return runProcess(['osascript','-e',`tell application "System Events" to ${expr}`],{timeoutMs:10_000});}if(await commandExists('xdotool')){const map:Record<string,string>={CMD:'super',COMMAND:'super',CTRL:'ctrl',CONTROL:'ctrl',ALT:'alt',OPTION:'alt',SHIFT:'shift',ENTER:'Return',RETURN:'Return',ESCAPE:'Escape',ESC:'Escape'};const key=[...shortcut.modifiers,shortcut.key].map((part)=>map[part]??part.toLowerCase()).join('+');return runProcess(['xdotool','key',key],{timeoutMs:10_000});}throw new Error('No Linux key backend found (install xdotool)');}
  async scroll(deltaY:number){if(process.platform==='darwin'){const wheel=Math.max(-100,Math.min(100,Math.round(-deltaY/100)));const script=`import CoreGraphics\nCGEvent(scrollWheelEvent2Source:nil,units:.line,wheelCount:1,wheel1:Int32(${wheel}),wheel2:0,wheel3:0)!.post(tap:.cghidEventTap)`;return runProcess(['swift','-e',script],{timeoutMs:20_000});}if(await commandExists('xdotool')){const button=deltaY>0?'5':'4',count=Math.max(1,Math.min(20,Math.ceil(Math.abs(deltaY)/100)));return runProcess(['xdotool','click','--repeat',String(count),button],{timeoutMs:10_000});}throw new Error('No Linux scroll backend found (install xdotool)');}
  async openApp(name:string){return process.platform==='darwin'?runProcess(['open','-a',name],{timeoutMs:15_000}):runProcess(['gtk-launch',name],{timeoutMs:15_000});}
}
