import Database from 'better-sqlite3';
import { mkdirSync } from 'node:fs';
import path from 'node:path';
import { randomUUID } from 'node:crypto';

export type MemoryKind='semantic'|'episodic'|'procedural'|'workspace'|'artifact';
export type MemoryRecord={id:string;kind:MemoryKind;namespace:string;content:string;importance:number;metadata:Record<string,unknown>;createdAt:string;updatedAt:string;score?:number};
export class MemoryStore{
  private readonly db:Database.Database; private fts=false;
  constructor(stateDir:string){mkdirSync(stateDir,{recursive:true});this.db=new Database(path.join(stateDir,'memory.sqlite'));this.db.pragma('journal_mode = WAL');this.db.exec(`CREATE TABLE IF NOT EXISTS memories(rowid INTEGER PRIMARY KEY AUTOINCREMENT,id TEXT UNIQUE NOT NULL,kind TEXT NOT NULL,namespace TEXT NOT NULL,content TEXT NOT NULL,importance INTEGER NOT NULL,metadata_json TEXT NOT NULL,created_at TEXT NOT NULL,updated_at TEXT NOT NULL);CREATE INDEX IF NOT EXISTS memories_namespace_kind ON memories(namespace,kind);`);try{this.db.exec(`CREATE VIRTUAL TABLE IF NOT EXISTS memory_fts USING fts5(content,namespace,content='memories',content_rowid='rowid');CREATE TRIGGER IF NOT EXISTS memories_ai AFTER INSERT ON memories BEGIN INSERT INTO memory_fts(rowid,content,namespace) VALUES(new.rowid,new.content,new.namespace); END;CREATE TRIGGER IF NOT EXISTS memories_ad AFTER DELETE ON memories BEGIN INSERT INTO memory_fts(memory_fts,rowid,content,namespace) VALUES('delete',old.rowid,old.content,old.namespace); END;CREATE TRIGGER IF NOT EXISTS memories_au AFTER UPDATE ON memories BEGIN INSERT INTO memory_fts(memory_fts,rowid,content,namespace) VALUES('delete',old.rowid,old.content,old.namespace);INSERT INTO memory_fts(rowid,content,namespace) VALUES(new.rowid,new.content,new.namespace); END;`);this.fts=true;}catch{this.fts=false;}}
  store(input:{kind:MemoryKind;namespace:string;content:string;importance?:number;metadata?:Record<string,unknown>}):MemoryRecord{const id=randomUUID(),now=new Date().toISOString(),importance=Math.max(0,Math.min(100,Math.round(input.importance??50)));this.db.prepare('INSERT INTO memories(id,kind,namespace,content,importance,metadata_json,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?)').run(id,input.kind,input.namespace,input.content,importance,JSON.stringify(input.metadata??{}),now,now);return{id,kind:input.kind,namespace:input.namespace,content:input.content,importance,metadata:input.metadata??{},createdAt:now,updatedAt:now};}
  search(query:string,options:{namespace?:string;kind?:MemoryKind;limit?:number}={}):MemoryRecord[]{const limit=Math.max(1,Math.min(100,options.limit??10));let rows:unknown[]=[];if(this.fts&&query.trim()){const tokens=query.trim().split(/\s+/).filter(Boolean).map((token)=>`"${token.replaceAll('"','""')}"`).join(' OR ');try{rows=this.db.prepare(`SELECT m.*,bm25(memory_fts) AS score FROM memory_fts JOIN memories m ON m.rowid=memory_fts.rowid WHERE memory_fts MATCH ? AND (? IS NULL OR m.namespace=?) AND (? IS NULL OR m.kind=?) ORDER BY score ASC,m.importance DESC LIMIT ?`).all(tokens,options.namespace??null,options.namespace??null,options.kind??null,options.kind??null,limit);}catch{rows=[];}}if(!rows.length){rows=this.db.prepare(`SELECT *,0 AS score FROM memories WHERE content LIKE ? AND (? IS NULL OR namespace=?) AND (? IS NULL OR kind=?) ORDER BY importance DESC,updated_at DESC LIMIT ?`).all(`%${query}%`,options.namespace??null,options.namespace??null,options.kind??null,options.kind??null,limit);}return rows.map((row)=>this.fromRow(row));}
  list(limit=50):MemoryRecord[]{return (this.db.prepare('SELECT *,0 AS score FROM memories ORDER BY updated_at DESC LIMIT ?').all(limit) as unknown[]).map((row)=>this.fromRow(row));}
  delete(id:string):boolean{return this.db.prepare('DELETE FROM memories WHERE id=?').run(id).changes>0;}
  close(){this.db.close();}
  private fromRow(value:unknown):MemoryRecord{const row=value as Record<string,unknown>;return{id:String(row.id),kind:String(row.kind) as MemoryKind,namespace:String(row.namespace),content:String(row.content),importance:Number(row.importance),metadata:JSON.parse(String(row.metadata_json)) as Record<string,unknown>,createdAt:String(row.created_at),updatedAt:String(row.updated_at),score:Number(row.score??0)};}
}
